name: Deploy
on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and Release
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install
      - run: yarn build

      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GB_TOKEN }}
      - name: Switch to Release Folder
        run: |
          cd build
          ls -la
          zip -r "${{ steps.tag_version.outputs.new_tag }}.release.zip" .
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/${{ steps.tag_version.outputs.new_tag }}.release.zip"
          token: ${{ secrets.GB_TOKEN }}
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}
